# Generated by Django 2.1.4 on 2019-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('address', models.TextField(max_length=500, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
